name: Build IPA

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create IPA
        run: |
          mkdir -p Payload
          echo '#!/bin/bash' > script.sh
          chmod +x script.sh
          zip -r standoff2cheat.ipa Payload
      - uses: actions/upload-artifact@v4
        with:
          name: ipa-file
          path: standoff2cheat.ipa
